### ISSUE TITLE
OSX - no sound (might not be loading sound pack)

### ISSUE THREAD

**Issue by jecowa** [prixt/soundsense-rs#1]
I'm on Mac OS 10.14.5 Mojave

It loads a window. - https://i.imgur.com/0QchJO5.png
I can read the "About" box. - https://i.imgur.com/WKW5jT6.png

It shows events happening in the Terminal window when I used this command: `./soundsense-rs-v1.3.0-osx -p "/Applications/Lazy Mac Pack v0.44.09/LNP/Utilities/soundsense/packs/default"` , but there's no sound. - https://i.imgur.com/cqQSByR.png

If I use this command instead to load soundsense-rs, `./soundsense-rs-v1.3.0-osx -p "/Applications/Lazy Mac Pack v0.44.09/LNP/Utilities/soundsense/packs"` , I get an error message:

>thread 'sound_thread' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
>note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

It gives the same error when running with the backtrace option.

If I try to use the GUI to load the sound pack, it gives me a notice in the terminal window:

>objc[15939]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa1b263d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10ef0bf50). One of the two will be used. Which one is undefined.
>thread 'sound_thread' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
>note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

There's no such notice when using the GUI to load the gamelog.txt.

**Comment by prixt** [comment]
Hi, just released v1.3.1 attempting to identify the issue. I don't have access to an OSX machine to test this, but I think I found where the error is coming from.
I suspect this has to do with the `rodio` crate and Apple devices. If that's the case, you'll see a  `Failed to get default audio output device.` error message. Could you test this?

**Comment by jecowa** [comment]
Awesome! That fixed it! Thank you!

**Comment by prixt** [comment]
wait it did?
well thank you for the bug report, glad I could help.
