### ISSUE TITLE
OSX - no GUI for Volume Control

### ISSUE THREAD

**Issue by jecowa** [prixt/soundsense-rs#2]
On the [example](http://i.imgur.com/fRSErTv.png) screenshot there's a fancy GUI for separately controlling the volumes weather, music, swords. I'm not seeing this in the Mac version.

Mac GUI - https://i.imgur.com/ObQcNVf.png

It's okay if it can't be fixed. I'm just happy it works at all now.

**Comment by prixt** [comment]
I think this is an issue with `webview`. Since I don't have access to a OSX machine to test, there isn't a good way for me do debug this.
Maybe I need to look into other GUI crates.

**Comment by prixt** [comment]
Hi! I just updated the dependent crates, `webview` included. Could you check if this fixed the issue?

**Comment by jecowa** [comment]
Sorry, there's still no GUI.

**Comment by prixt** [comment]
welp. well I'll look into other options.

**Comment by prixt** [comment]
@jocowa Hi, me again. Reworked the UI handling a bit. Could you check the v1.3.3 release?

**Comment by jecowa** [comment]
It behaves the same as 1.3.2 on both Mac and Linux. No volume controls and Linux gives the `Failed to load module "appmenu-gtk-module"` error. I don't know much about Linux, but I tried downloading the appmenu-gtk-module, but it acted like it was already installed.

**Comment by prixt** [comment]
@jecowa Ok, release v1.3.5 is out. If *this* doesn't fix it, I might just throw my towel with `web-view`.

**Comment by jecowa** [comment]
Thanks! The GUI shows up now.
https://i.imgur.com/2MUdCB2.png
The controls seem to work, though, not even the "all" volume.

**Comment by prixt** [comment]
@jecowa Fixed volume sliders. Was related to a bug where new sounds added to a channel didn't match the channel's volume. I hope this one is it!

**Comment by jecowa** [comment]
Yes, that fixes it. In arena mode I can use the "all" slider to control master volume, the "misc" slider to control battle sounds, and the "music" slider to control music.

**Comment by prixt** [comment]
🎉 HOORAY! 🎉
