### ISSUE TITLE
Soundpack.zip download & capability to read from .zip directly?

### ISSUE THREAD

**Issue by prixt** [prixt/soundsense-rs#5]
Should soundsense-rs have the ability to download the soundpack.zip, and read the zip file directly?
These features would enhance the usability of soundsense-rs, but will probably increase the binary size and memory usage.

**Comment by jecowa** [comment]
I don't think it needs to be able to read directly from a zip file. On OSX, there is an un-zip utility built-in. It's just `unzip filename.zip` in the Terminal.

The "official sound pack" is also a little outdated. Maybe it would be good to put it on GitHub and let people make changes to it. The "official sound pack" is licensed under GNU GPL v3. Falcn on the forums has made a few updates for it to work with features added in DF v0.44.

**Comment by prixt** [comment]
Perhaps just linking to the SoundSense website and a few soundpack forks will suffice?

**Comment by jecowa** [comment]
Yeah, that's good.

**Comment by prixt** [comment]
Added links to zwei's and @jecowa's soundpack in v1.3.7

**Comment by jecowa** [comment]
The links are working now on Mac in SoundSense-RS v1.3.7. Before 1.3.7, none of the buttons in the options menu did anything except for the "About" box.
